import Head from 'next/head'
import { useState, useEffect } from 'react';
import { ethers } from 'ethers'
import MintingTokens from '../src/artifacts/contracts/MintingTokens.sol/MintingTokens.json'

const mintingTokensAddress = process.env.NEXT_PUBLIC_MINTING_TOKENS_ADDRESS

export default function Home() {

  const [userAccount, setUserAccount] = useState()
  const [accountSelected, setAccountSelected] = useState('')
  const [amount, setAmount] = useState()
  const [balance, setBalance] = useState(0)
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    async function getAccount () {
      setLoading(true)
      const [account] = await requestAccount()
      setAccountSelected(account)
      setLoading(false)
    }
    getAccount()
  }, [])

  function checkWindowEtherumIsValid() {
    return typeof window.ethereum !== 'undefined'
  }

  async function requestAccount() {
   return await window.ethereum.request({ method: 'eth_requestAccounts' });
  }

  async function getBalance() {
    if(checkWindowEtherumIsValid()) {
      setLoading(true)
      const [account] = await requestAccount()
      const provider = new ethers.providers.Web3Provider(window.ethereum);
      const contract = new ethers.Contract(mintingTokensAddress, MintingTokens.abi, provider)
      const balanceData = await contract.balanceOf(account) 
      setBalance(balanceData.toString())
      setLoading(false)
    }
  }

  async function sendCoins() {
    if(checkWindowEtherumIsValid()) {
      try {
        setLoading(true)
        const provider = new ethers.providers.Web3Provider(window.ethereum);
        const signer = provider.getSigner();
        const contract = new ethers.Contract(mintingTokensAddress, MintingTokens.abi, signer)
        const transaction = await contract.transfer(userAccount, amount)
        await transaction.wait();
        setLoading(false)
        alert(`Coins successfully sent to ${userAccount}`)
        setUserAccount('')
        setAmount('')
      } catch (error) {
        setLoading(false)
        alert(error.data.message)
      }
    }
  }


  if(loading) {
    return (
      <div className="bg-gray-200 min-w-screen min-h-screen flex items-center justify-center px-5 py-5">
        <svg role="status" className="w-8 h-8 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
          <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"/>
          <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"/>
        </svg>
      </div>
    )
  }

  return (
    <div className="bg-gray-200">
      <Head>
        <title>Next app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-w-screen min-h-screen flex items-center justify-center px-5 py-5">
        <div className="bg-white text-gray-800 rounded-xl shadow-lg overflow-hidden relative flex flex-col p-6 justify-center items-center">
          <div className="text-3xl font-bold ">
             My First Ethereum Token by Lorena Porphirio   
          </div>
          <div id="empty-cover-art" className="shadow-md py-5 h-28 rounded w-56 bg-blue-100 text-center opacity-50 md:border-solid md:border-2  md:border-blue-800 m-6">
            <center>
              <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Ethereum-icon-purple.svg/1200px-Ethereum-icon-purple.svg.png" className="h-16 " alt="img etherum logo" />
            </center>
            <span className="font-mono bg-white rounded">{`${accountSelected.slice(0,6)}...${accountSelected.slice(35,accountSelected.length)}`}</span>
          </div>

          <strong>Total Token: {balance} LPT</strong>
          <button 
            className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 my-4"
            onClick={getBalance}
          >
            Get Balance
          </button>
          <div>
            <label htmlFor="accountId" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Account ID</label>
            <input id="accountId" 
              className="bg-gray-50 border w-80 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" 
              placeholder="Account ID"
              value={userAccount}
              onChange={e => setUserAccount(e.target.value)}
              required 
            />
          </div>
          <div className="mt-8">
            <label htmlFor="amount" className="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Amount</label>
            <input id="amount" 
              className="bg-gray-50 border w-80 border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block p-2.5" 
              placeholder="Amount"
              value={amount}
              onChange={e => setAmount(e.target.value)}
              required 
            />
          </div>
          <button 
            className="w-80 text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center my-4"
            onClick={sendCoins}
          >
            Send Coins
          </button>
        </div>
      </main>
    </div>
  )
}
